[project]
name = "Game Utils"
version = "0.0.1"
authors = [
    {
        name="Bee Hall", 
        email="bhall1224@gmail.com"
    }
]
description = ""
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent:
]

[project.urls]
"Homepage" = "https://gitlab.com/madmadam/games/game_utils"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"